### ISSUE TITLE
send a gzipped index.html if a directory is requested

### ISSUE THREAD

**Issue by obazoud** [tomgco/gzippo#12]
When I use express + gzippo, http://www.mywebsite.com/index.html is compressed but not http://www.mywebsite.com/
As I can see in source, if filename is a directory, you delegate it to express.
I think that it should be interesting to try to send index.html, it if exists, and gzip it.
Let me know what you think.

**Comment by tomgco** [comment]
This is because gzippo doesn't support streaming files only static content files. This is being worked into a new version of connect which express is based on.
