### ISSUE TITLE
Node 0.6+ Compatibility

### ISSUE THREAD

**Issue by niftylettuce** [tomgco/gzippo#13]
`compress` not working per https://github.com/waveto/node-compress/pull/13

**Comment by niftylettuce** [comment]
Also the required dependencies should be updated/tested, e.g. `connect` dependency is set to an older version which is only compatible with `node` < 0.5.

**Comment by tomgco** [comment]
I was initially working on a version of gzippo which included the zlib api in node 0.6 to replace compress for 0.6 onwards which would add windows support aswell. Hopefully I will have the chance to update it in the following weeks.

**Comment by tomgco** [comment]
Version 0.1.0 of gzippo has now been released. This should now work with node >= 0.6! :]

**Comment by niftylettuce** [comment]
Great work!  Thank you!!!
