### ISSUE TITLE
Going to a directory path without trailing slash exposes system path.

### ISSUE THREAD

**Issue by serby** [tomgco/gzippo#14]
If you go to:

http://www.tomg.co/js

Gzippo passes the filename to the staticSend via pass() on line 159. express then does a 301 and redirect to this path. 

Resulting in:

http://www.tomg.co/var/application/Tom/PersonalSite/public/js/

This is a pretty major security concern as it exposes private information about your system.

A directory check should be performed first or the url.pathname should be send to static send for the redirect.

**Comment by tomgco** [comment]
This has now been fixed in 0.1.1 and 0.0.8

**Comment by serby** [comment]
We think that this is still an issue and should be reopened
