### ISSUE TITLE
Any update on the streaming support

### ISSUE THREAD

**Issue by dmmalam** [tomgco/gzippo#15]
we'd love to use gzippo to squish dynamic html and json requests.

**Comment by tomgco** [comment]
I have backported streaming gzip support from connect 2.X into gzippo 0.1.2 you can access this by using
`app.use(gzippo.compress());`
This will not be maintained by me, however up until the point when connect 2.X is released or the module is backported i will merge any changes back to gzippo.

**Comment by dmmalam** [comment]
Awesome, I was just looking at the compress stuff in connect.
Is yours compatible with node 0.4.x

Dharmesh

On 26 Dec 2011, at 13:52, Tom Gallacher
reply@reply.github.com
wrote:

**Comment by tomgco** [comment]
No this is using the zlib api found in 0.6 and upwards. I do have a streamingGzip branch https://github.com/tomgallacher/gzippo/tree/streamingGzip/lib which i believe works however because of the overhead it seems to be very inefficient which I will not be deploying.
