### ISSUE TITLE
Cahcing in redis /  memchacd?

### ISSUE THREAD

**Issue by dmmalam** [tomgco/gzippo#16]
How does gzippo cache compressed file? it is all in memory on the current process?

It would be useful to have a interface which can store recently compressed files / requests in redis/memchached so that a cluster of node process can share the precompressed objects.

**Comment by tomgco** [comment]
Been thinking about starting this again, however requires a full refactor of the code base and at the moment I do not have the time to start this. I believe someone forked and started working on an implementation however haven't heard anything yet.

**Comment by tomgco** [comment]
I have started work on a version which supports this, it is currently in the `develop` branch and I have started work on `gzippo-redis` https://github.com/tomgallacher/gzippo-redis however this currently is broken. Feel free to fork and to get it working =]
