### ISSUE TITLE
dependencies not correctly defined.

### ISSUE THREAD

**Issue by devrim** [tomgco/gzippo#21]
gzippo requires compress library to be there, not mentioned in dependencies.

(then compress requires these two libraries yum install gcc-c++ zlib-devel if anyone experiences install issues on centos)

**Comment by tomgco** [comment]
Which version of Nodejs are you running? With <= 0.4 compress is defined in the [package.json](https://github.com/tomgallacher/gzippo/blob/gzippo0.0.X/package.json) However compress does depend on `gcc-c++` `zlib-devel` and I will add that to the readme!
