### ISSUE TITLE
incompatible with express-resource

### ISSUE THREAD

**Issue by panosru** [tomgco/gzippo#26]
Hi, it seems that it is incompatible with [express-resource](https://github.com/visionmedia/express-resource) as I mentioned [here](https://github.com/visionmedia/express-resource/issues/52#issuecomment-4034465)

**Comment by panosru** [comment]
anyone?

**Comment by tomgco** [comment]
Looks like it was fixed here https://github.com/senchalabs/connect/commit/b03e5168885af86543804efd832118385fe4b33b#lib/middleware/compress.js I will update this when I have a chance. sorry for the delay in getting back to you.

**Comment by panosru** [comment]
@tomgallacher thanks for your reply :)
