### ISSUE TITLE
http://tomg.co/gzippo link to github is wrong

### ISSUE THREAD

**Issue by marado** [tomgco/gzippo#29]
http://tomg.co/gzippo points to the (broken) https://github.com/tomgallacher/gzippo link when it should point to https://github.com/tomgco/gzippo . I'm submitting the bug here since I'm assuming that that page is still the "official gzippo website" - as pointed out by this github repo.

**Comment by tomgco** [comment]
Should be fixed now, Thanks! Thought standardising my account names wasn't going to be this hard! :P
