### ISSUE TITLE
compress.js doesn't seem to be working

### ISSUE THREAD

**Issue by goldfire** [tomgco/gzippo#31]
I've tried on both Express 2.6.9 and 3.0.0alpha2 with Node 0.6.15, but when I view the inspector, only the static files are getting gzipped. What is interesting is that I also tried using the compress middleware that comes with Express 3, and I couldn't get that to work either.

My config:

``` javascript
app.configure(function(){
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.set('view options', {cache: true});
    app.use(express.bodyParser());
    app.use(express.cookieParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(express.staticCache());
    //app.use(express.static(__dirname + '/public'));
    //app.use(express.compress());
    app.use(gzippo.staticGzip(__dirname + '/public'));
    app.use(gzippo.compress());
});
```

Is there something else required outside of the configuration to make it work?

**Comment by tomgco** [comment]
Have you tried placing the the compress commands before `app.use(app.router);`? I believe that is what I have on my sites, however it is possible it is not working for me?

**Comment by goldfire** [comment]
Yes, that took care of it. Thank you very much!
