### ISSUE TITLE
Major security issue with version 0.1.3

### ISSUE THREAD

**Issue by murvinlai** [tomgco/gzippo#32]
I use gzippo@0.1.3  and I create the server like that:

```
 app = express.createServer(
             gzip.staticGzip(__dirname + '/public', {maxAge:5000 }),
             express.cookieParser(),
             express.bodyParser()
    );
```

If i go to the url like that: https://www.myself.com/../../../../../etc/rsyslog.conf    or other path, I can see any system file.  

If I upgrade to gzippo@0.1.4  the problem seems not there.  However, I don't know if 0.1.4 solve that problem purposely or it just disappear for that version.

Please test this module carefully.

**Comment by tomgco** [comment]
This was fixed in #14 and #24 and deployed in @0.1.4

When installing older versions a `warn` is shown displaying: `npm WARN deprecated gzippo@0.1.3: critical bug fixed in v0.1.4`

**Comment by murvinlai** [comment]
Thanks.

**Comment by gilad61** [comment]
Hi,
I would like to reopen this issue, as 0.1.4 still has it.
If I go to any url with '..' in it I can navigate back through the file system and get any file.
For example - http://localhost:8000/../../someFolder/someFile.txt

In connect they have a test to make sure you don't go back in the directories hierarchy:
// malicious path
if (root && 0 != path.indexOf(root)) return utils.forbidden(res);

where 'root' is the base dir, and 'path' is the full file path of the requested file.

Thanks!

**Comment by dcolens** [comment]
am still seeing this issue in 0.1.4 ...

**Comment by wmertens** [comment]
Please fix this, here's how connect static does it:
 https://github.com/senchalabs/connect/blob/master/lib/middleware/static.js#L143

**Comment by murvinlai** [comment]
I just found out another problem..

http://local/etc/shadow  

is another leak.

**Comment by wmertens** [comment]
@murvinlai Same problem, gzippo doesn't check if the normalized path is under the paths it should be serving.

Also, don't run your node scripts as root - ever.

**Comment by tomgco** [comment]
@murvinlai @wmertens What version of connect are you using and gzippo, as I cannot seem to replicate this problem. Also could you run the tests as well and let me know if anything fails? 

Thanks

**Comment by wmertens** [comment]
I see that this was added:
https://github.com/tomgco/gzippo/blob/master/lib/staticGzip.js#L158

but the gzippo version 0.1.4 I was testing at the time didn't have it.
