### ISSUE TITLE
Security issue - can go back the file system hierarchy in 0.1.4

### ISSUE THREAD

**Issue by gilad61** [tomgco/gzippo#33]
If I go to any url with '..' in it I can navigate back through the file system and get any file.
For example - http://localhost:8000/../../someFolder/someFile.txt

In connect they have a test to make sure you don't go back in the directories hierarchy:
// malicious path
if (root && 0 != path.indexOf(root)) return utils.forbidden(res);

where 'root' is the base dir, and 'path' is the full file path of the requested file.

Thanks!

**Comment by tomgco** [comment]
Should be fixed in 0.1.6
