### ISSUE TITLE
Plans for 0.7.x/0.8.x branch?

### ISSUE THREAD

**Issue by zzen** [tomgco/gzippo#40]
I noticed gzippo fails to compile on 0.7.12 - and even plainly declares that in package.json. Is there a 0.7/8 version in the works?

**Comment by tomgco** [comment]
Indeed it should work with 0.8 and will be updated so that it does, That was put to ensure that no incompatibilities occurred - around the 0.4 -> 0.6 releases. I will leave this open to ensure that 0.8 is tested. Thanks for letting me know about this!

**Comment by uipoet** [comment]
0.8 was released and this issue has yet to be resolved.
